# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Beer.destroy_all
Brewery.destroy_all

zero_gravity = Brewery.create(name: "Zero Gravity Craft Brewery", address: "716 Pine Street", city: "Burlington", state: "Vermont", zip_code: "05401", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_5863")
bbc = Brewery.create(name: "Burlington Beer Company", address: "25 Omega Drive Suite 150", city: "Williston", state: "Vermont", zip_code: "05495", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_14675")
new_anthem = Brewery.create(name: "New Anthem Beer Project", address: "116 Dock Street", city: "Wilmington", state: "North Carolina", zip_code: "28401", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_30750")
flytrap = Brewery.create(name: "Flytrap Brewing", address: "319 Walnut Street", city: "Wilmington", state: "North Carolina", zip_code: "28401", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_21157")
wbc = Brewery.create(name: "Wilmington Brewing Company", address: "824 S Kerr Ave", city: "Wilmington", state: "North Carolina", zip_code: "28403", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_22843")
ironclad = Brewery.create(name: "Ironclad Brewery", address: "115 N. 2nd Street", city: "Wilmington", state: "North Carolina", zip_code: "28401", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_22969")
alchemist = Brewery.create(name: "The Alchemist", address: "100 Cottage Club Rd", city: "Stowe", state: "Vermont", zip_code: "05672", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_22969")
raleigh = Brewery.create(name: "Raleigh Brewing Company", address: "3709 Neil Street", city: "Raleigh", state: "North Carolina", zip_code: "27607", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_16292")
appmtn = Brewery.create(name: "Appalachian Mountain Brewery", address: "163 Boone Creek Dr", city: "Boone", state: "North Carolina", zip_code: "28607", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_16180")
clt = Brewery.create(name: "NoDa Brewing Company", address: "2229 N Davidson St", city: "Charlotte", state: "North Carolina", zip_code: "28205", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_13551")
farmville = Brewery.create(name: "The Duck-Rabbit Craft Brewery", address: "4519 W Pine St", city: "Farmville", state: "North Carolina", zip_code: "28227", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_5175")

Beer.create(brewery: zero_gravity, name: "Zero Gravity Conehead IPA", style: "IPA", abv: 5.7, rating: 3.73, description: "Our single-hopped Wheat IPA. This beer was launched as part of our I.P.April– a month long celebration of hoppy brews–and we decided to brew it with a different hop each year. Until we brewed it with Citra and then, well, we never turned back. Completely satisfyingly awesome in its crispiness and over-all well-rounded hopaliciousness. This beer might just be your Rushmore.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_63273")
Beer.create(brewery: bbc, name: "Uncanny Valley", style: "New England IPA", abv: 7.0, rating: 3.84, description: "El Dorado and Azacca hops", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_456378")
Beer.create(brewery: bbc, name: "Creatures of Magic", style: "New England IPA", abv: 6.5, rating: 3.83, description: "New England oatmeal India pale ale.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/d_beer_img_default.png,f_auto/beer_648083")
Beer.create(brewery: new_anthem, name: "Throwing Shade", style: "New England IPA", abv: 6.9, rating: 4.30, description: "Cascade and Mosaic.", thumbs_up: "or", image_url: "https://cdn.beeradvocate.com/im/c_beer_image.gif")
Beer.create(brewery: flytrap, name: "Flytrap Porter", style: "Porter", abv: 5.9, rating: 3.40, description: "Clear, bright, very dark reddish brown colour with a small brown head; faint aroma of milk chocolate; balanced flavour with a long, light bitter finish.", thumbs_up: "or", image_url: "https://pbs.twimg.com/profile_images/378800000827015749/340b36100b82464b25db184bc6bf003d.jpeg")
Beer.create(brewery: new_anthem, name: "11th and Folsom", style: "Double New England IPA", abv: 7.0, rating: 3.87, description: "AMARILLO, CITRA, ELDORADO, MOSAIC…", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_743111")
Beer.create(brewery: ironclad, name: "Coffee Porter", style: "Porter", abv: 7.7, rating: 3.30, description: "Our coffee porter is presented as a brown porter with a heavy dose of Java Estates espresso roast coffee. It is a dark brown colored beer with an off white to tan head. This porter drinks with a moderate malt roastiness and hints of chocolate.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_331981")
Beer.create(brewery: wbc, name: "Vacation Chasin'", style: "New England IPA", abv: 8.0, rating: 3.90, description: "Milkshake IPA brewed/w Peaches.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_678078")
Beer.create(brewery: wbc, name: "Some New IPA", style: "New England IPA", abv: 7.4, rating: 4.00, description: "Juicy IPA.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_678079")
Beer.create(brewery: wbc, name: "Dinosaur Parade", style: "Session IPA", abv: 5.8, rating: 3.75, description: "Session IPA - Double Dry Hopped.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_746714")
Beer.create(brewery: bbc, name: "It's Complicated Being a Wizard", style: "Double New England IPA", abv: 8.0, rating: 3.77, description: "Poured a cloudy golden color with a medium sized head. Citrus, caramel, floral, and some fruits.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_309808")
Beer.create(brewery: bbc, name: "Bring Forth the Mollusk", style: "Porter", abv: 5.5, rating: 3.56, description: "Collaboration with Proclamation Ale Company. Brewed with Applewood smoked malt and Rhode Island oysters. A rich full bodied porter with a touch of smoke and sea breeze.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_460325")
Beer.create(brewery: alchemist, name: "Heady Topper", style: "Double New England IPA", abv: 8.0, rating: 4.39, description: "An American Double IPA, packed with over 120 IBU!", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_32329")
Beer.create(brewery: raleigh, name: "Not Another", style: "New England IPA", abv: 6.1, rating: 3.36, description: "Very cloudy almost chalky appearance coming out of the can.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_641803")
Beer.create(brewery: appmtn, name: "Mountain Sunrise IPA", style: "New England IPA", abv: 6.5, rating: 3.80, description: "Very very very pretty pour. Hops: Azzaca, Mosaic, Citra.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_760569")
Beer.create(brewery: appmtn, name: "Long Leaf IPA", style: "IPA", abv: 7.1, rating: 3.44, description: "An Angelo-American-style IPA, with a carefully blended floral and citrus aroma. a mouthful of hop flavor is complimented by a malty backbone, leaving you with a subdued lingering bitterness.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_202160")
Beer.create(brewery: clt, name: "Drop 'n Roll IPA", style: "IPA", abv: 7.2, rating: 3.88, description: "Our west coast style IPA hits you with a ton of juicy hop flavor that shines out from a substantial and complex malt backbone. We use Citra, Amarillo, Centennial, Warrior and Chinook in 10 separate additions to provide the intense hop blast found within this can!", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_156010")
Beer.create(brewery: farmville, name: "Duck-Rabbit Milk Stout", style: "Stout", abv: 5.7, rating: 3.59, description: "A traditional full-bodied stout brewed with lactose (milk sugar). The subtle sweetness imparted by the lactose balances the sharpness of the highly roasted grains which give this delicious beer its black color.", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_38879")
Beer.create(brewery: wbc, name: "Seasonal Bartender", style: "New England IPA", abv: 7.8, rating: 3.90, description: "Tropical Milkshake India Pale Ale brewed with guava, pineapple, and mangoes…", thumbs_up: "or", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_696426")
