# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Beer.destroy_all
Brewery.destroy_all

zero_gravity = Brewery.create(name: "Zero Gravity Craft Brewery", address: "716 Pine Street", city: "Burlington", state: "Vermont", zip_code: "05401", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_5863")
bbc = Brewery.create(name: "Burlington Beer Company", address: "25 Omega Drive Suite 150", city: "Williston", state: "Vermont", zip_code: "05495", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_14675")
new_anthem = Brewery.create(name: "New Anthem Beer Project", address: "116 Dock Street", city: "Wilmington", state: "North Carolina", zip_code: "28401", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_30750")
flytrap = Brewery.create(name: "Flytrap Brewing", address: "319 Walnut Street", city: "Wilmington", state: "North Carolina", zip_code: "28401", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_21157")
wbc = Brewery.create(name: "Wilmington Brewing Company", address: "824 S Kerr Ave", city: "Wilmington", state: "North Carolina", zip_code: "28403", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_22843")
ironclad = Brewery.create(name: "Ironclad Brewery", address: "115 N. 2nd Street", city: "Wilmington", state: "North Carolina", zip_code: "28401", image_url: "https://res.cloudinary.com/ratebeer/image/upload/w_144,c_fill,d_Default_Brewery_q4okin.png,f_auto/brew_22969")

Beer.create(brewery: zero_gravity, name: "Zero Gravity Conehead IPA", style: "IPA", abv: 5.7, rating: 3.73, description: "Our single-hopped Wheat IPA. This beer was launched as part of our I.P.April– a month long celebration of hoppy brews–and we decided to brew it with a different hop each year. Until we brewed it with Citra and then, well, we never turned back. Completely satisfyingly awesome in its crispiness and over-all well-rounded hopaliciousness. This beer might just be your Rushmore.", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_63273")
Beer.create(brewery: bbc, name: "Uncanny Valley", style: "New England IPA", abv: 7.0, rating: 3.84, description: "El Dorado and Azacca hops", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_456378")
Beer.create(brewery: bbc, name: "Creatures of Magic", style: "New England IPA", abv: 6.5, rating: 3.83, description: "New England oatmeal India pale ale.", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/d_beer_img_default.png,f_auto/beer_648083")
Beer.create(brewery: new_anthem, name: "He's So Fine", style: "New England IPA", abv: 7.3, rating: 4.30, description: "Cascade and Mosaic.", thumbs_up: "not_yet", image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.teepublic.com%2Fsticker%2F6588321-add-me&psig=AOvVaw2240suxFTSmXx1PVJiF3yz&ust=1599115099150000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIjH05zuyesCFQAAAAAdAAAAABAE")
Beer.create(brewery: flytrap, name: "Flytrap Porter", style: "Porter", abv: 5.9, rating: 3.40, description: "Clear, bright, very dark reddish brown colour with a small brown head; faint aroma of milk chocolate; balanced flavour with a long, light bitter finish.", thumbs_up: "not_yet", image_url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.teepublic.com%2Fsticker%2F6588321-add-me&psig=AOvVaw2240suxFTSmXx1PVJiF3yz&ust=1599115099150000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIjH05zuyesCFQAAAAAdAAAAABAE")
Beer.create(brewery: new_anthem, name: "11th and Folsom", style: "Double New England IPA", abv: 7.0, rating: 3.87, description: "AMARILLO, CITRA, ELDORADO, MOSAIC…", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_743111")
Beer.create(brewery: ironclad, name: "Coffee Porter", style: "Porter", abv: 7.7, rating: 3.30, description: "Our coffee porter is presented as a brown porter with a heavy dose of Java Estates espresso roast coffee. It is a dark brown colored beer with an off white to tan head. This porter drinks with a moderate malt roastiness and hints of chocolate.", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_331981")
Beer.create(brewery: wbc, name: "Vacation Chasin'", style: "New England IPA", abv: 8.0, rating: 3.90, description: "Milkshake IPA brewed/w Peaches.", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_678078")
Beer.create(brewery: wbc, name: "Some New IPA", style: "New England IPA", abv: 7.4, rating: 4.00, description: "Juicy IPA.", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_678079")
Beer.create(brewery: wbc, name: "Dinosaur Parade", style: "Session IPA", abv: 5.8, rating: 3.75, description: "Session IPA - Double Dry Hopped.", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_746714")
Beer.create(brewery: bbc, name: "It's Complicated Being a Wizard", style: "Double New England IPA", abv: 8.0, rating: 3.77, description: "Poured a cloudy golden color with a medium sized head. Citrus, caramel, floral, and some fruits.", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_309808")
Beer.create(brewery: bbc, name: "Bring Forth the Mollusk", style: "Porter", abv: 5.5, rating: 3.56, description: "Collaboration with Proclamation Ale Company. Brewed with Applewood smoked malt and Rhode Island oysters. A rich full bodied porter with a touch of smoke and sea breeze.", thumbs_up: "not_yet", image_url: "https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_460325")
